param(
    [string]$SourceFile = "$PSScriptRoot\..\.tools\reference\WindowDirection.swift",
    [string]$DefaultsFile = "$PSScriptRoot\..\.tools\reference\Defaults.swift"
)
$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path "$PSScriptRoot\..").Path
$revision = 'df26d565e07c82e156b8f1c361bdcf428f32e3a4'
$url = "https://raw.githubusercontent.com/mrkai77/Loop/$revision/Loop/Window%20Management/Window%20Action/WindowDirection.swift"
if (-not (Test-Path -LiteralPath $SourceFile)) {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $SourceFile) | Out-Null
    Invoke-WebRequest -UseBasicParsing $url -OutFile $SourceFile
}
$source = [System.IO.File]::ReadAllText((Resolve-Path $SourceFile))
function Convert-Scalar([string]$Expression) {
    $parts = $Expression.Trim() -split '\s*/\s*'
    if ($parts.Count -gt 2 -or ($parts | Where-Object { $_ -notmatch '^\d+(\.\d+)?$' })) { throw "Unsupported source expression: $Expression" }
    $value = [double]::Parse($parts[0], [System.Globalization.CultureInfo]::InvariantCulture)
    if ($parts.Count -eq 2) { $value /= [double]::Parse($parts[1], [System.Globalization.CultureInfo]::InvariantCulture) }
    return $value
}
function Convert-ActionName([string]$Name) {
    return [regex]::Replace($Name, '([a-z0-9])([A-Z])', '$1_$2').ToLowerInvariant()
}
$pattern = 'case \.(?<name>\w+): \.init\(x: (?<x>[^,]+), y: (?<y>[^,]+), width: (?<width>[^,]+), height: (?<height>[^\)]+)\)'
$frames = @([regex]::Matches($source, $pattern) | ForEach-Object {
    [ordered]@{
        action = Convert-ActionName $_.Groups['name'].Value
        x = Convert-Scalar $_.Groups['x'].Value
        y = Convert-Scalar $_.Groups['y'].Value
        width = Convert-Scalar $_.Groups['width'].Value
        height = Convert-Scalar $_.Groups['height'].Value
    }
})
if ($frames.Count -lt 25) { throw 'Source extraction found too few frame definitions' }
$fixture = [ordered]@{
    source = $url
    revision = $revision
    source_sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $SourceFile).Hash.ToLowerInvariant()
    attribution = 'Loop, Kai Azim and contributors, GPL-3.0. Generated by tools/Generate-SourceFixtures.ps1.'
    frames = $frames
}
$fixtureRoot = Join-Path $projectRoot 'tests\fixtures'
New-Item -ItemType Directory -Force -Path $fixtureRoot | Out-Null
[System.IO.File]::WriteAllText((Join-Path $fixtureRoot 'loop-frames.json'), ($fixture | ConvertTo-Json -Depth 5))
$enumPrefix = $source.Substring(0, $source.IndexOf('// These are used'))
$actions = @([regex]::Matches($enumPrefix, '(\w+) = "(\w+)"') | ForEach-Object { $_.Groups[1].Value })
$inventory = [ordered]@{ revision = $revision; source = $url; actions = $actions }
[System.IO.File]::WriteAllText((Join-Path $fixtureRoot 'loop-actions.json'), ($inventory | ConvertTo-Json -Depth 4))
$defaultsUrl = "https://raw.githubusercontent.com/mrkai77/Loop/$revision/Loop/Extensions/Defaults%2BExtensions.swift"
if (-not (Test-Path -LiteralPath $DefaultsFile)) {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $DefaultsFile) | Out-Null
    Invoke-WebRequest -UseBasicParsing $defaultsUrl -OutFile $DefaultsFile
}
if (Test-Path -LiteralPath $DefaultsFile) {
    $defaults = [System.IO.File]::ReadAllText((Resolve-Path $DefaultsFile))
    $settings = @([regex]::Matches($defaults, 'static let (\w+)') | ForEach-Object { $_.Groups[1].Value } | Select-Object -Unique)
    $settingsInventory = [ordered]@{
        revision = $revision
        source_file = 'Defaults+Extensions.swift'
        source = $defaultsUrl
        attribution = 'Loop, Kai Azim and contributors, GPL-3.0. Generated by tools/Generate-SourceFixtures.ps1.'
        source_sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $DefaultsFile).Hash.ToLowerInvariant()
        settings = $settings
    }
    [System.IO.File]::WriteAllText((Join-Path $fixtureRoot 'loop-settings.json'), ($settingsInventory | ConvertTo-Json -Depth 4))
}
"status: generated`nframe_fixtures: $($frames.Count)`nsource_actions: $($actions.Count)"
